backend:
  name: git-gateway
  branch: master
media_folder: src/assets
public_folder: assets/images
collections:
  - name: "pages"
    label: "Pages"
    label_singular: "Image" # Used in the UI, ie: "New Post"
    folder: "content/blog"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string"}
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "isDisplay", name: "isDisplay", widget: "boolean", default: false }
      - { label: "Cover", name: "cover", widget: "image"}
      - { label: "Tags", name: "tags", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown"}
  - name: "gallery"
    label: "Gallery"
    label_singular: "Image" # Used in the UI, ie: "New Post"
    folder: "content/gallery"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string"}
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "isDisplay", name: "isDisplay", widget: "boolean", default: false }
      - { label: "Cover", name: "cover", widget: "image"}
      - { label: "Tags", name: "tags", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown"}
  - name: "home"
    label: "Home"
    label_singular: "Image" # Used in the UI, ie: "New Post"
    folder: "content/home"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string"}
      - { label: "Phone Number", name: "phone", widget: "string"}
      - { label: "Headline", name: "headline", widget: "string"}
      - { label: "Cover", name: "cover", widget: "image"}
  - name: "special"
    label: "Special"
    label_singular: "Image" # Used in the UI, ie: "New Post"
    folder: "content/special"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string"}
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Cover", name: "cover", widget: "image"}
      - { label: "Body", name: "body", widget: "markdown"}
  - name: "aboutImages"
    label: "About Images"
    label_singular: "Image" # Used in the UI, ie: "New Post"
    folder: "content/aboutImages"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string"}
      - { label: "Image", name: "image", widget: "image"}
  - name: "about"
    label: "About"
    label_singular: "About" # Used in the UI, ie: "New Post"
    folder: "content/about"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string"}
      - { label: "Body", name: "body", widget: "markdown"}
  - name: "studioImages"
    label: "Studio Images"
    label_singular: "Image" # Used in the UI, ie: "New Post"
    folder: "content/studioImages"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string"}
      - { label: "Image", name: "image", widget: "image"}
  - name: "studio"
    label: "Studio"
    label_singular: "Studio" # Used in the UI, ie: "New Post"
    folder: "content/studio"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string"}
      - { label: "Body", name: "body", widget: "markdown"}

