backend:
  name: git-gateway
  branch: master
media_folder: src/assets
public_folder: assets/images
collections:
  - name: "gallery"
    label: "Gallery"
    label_singular: "Image" # Used in the UI, ie: "New Post"
    folder: "content/gallery"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string"}
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "SEO Title", name: "seotitle", widget: "string"}
      - { label: "SEO Description", name: "seodescription", widget: "string"}
      - { label: "isDisplay", name: "isDisplay", widget: "boolean", default: false }
      - { label: "Cover", name: "cover", widget: "image"}
      - { label: "Tags", name: "tags", widget: "string" }

  - name: "home"
    label: "Home"
    label_singular: "Home" # Used in the UI, ie: "New Post"
    folder: "content/home"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string"}
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "SEO Title", name: "seotitle", widget: "string"}
      - { label: "SEO Description", name: "seodescription", widget: "string"}
      - { label: "Body", name: "body", widget: "markdown", required: false }
      - label: "home Sections"
        name: "homeSections"
        label_singular: "home Section"
        widget: 'list'
        types:
          - label: "About Section"
            name: "aboutSection"
            widget: object
            fields:
              - { label: "Title", name: "title", widget: "string"}
              - { label: "Publish Date", name: "date", widget: "datetime" }
              - { label: "Cover", name: "cover", widget: "image", required: false }
              - { label: "Body", name: "body", widget: "markdown", required: false }
              - { label: "About images", name: "aboutImages", widget: "list", fields: [{label: "Image", name: "image", widget: "image"}], required: false }
          - label: "Special Section"
            name: "specialSection"
            label_singular: "special Section"
            widget: object
            fields:
              - { label: "Title", name: "title", widget: "string"}
              - { label: "Publish Date", name: "date", widget: "datetime" }
              - { label: "Cover", name: "cover", widget: "image", required: false }
              - { label: "Body", name: "body", widget: "markdown", required: false }

  - name: "about"
    label: "About"
    label_singular: "About" # Used in the UI, ie: "New Post"
    folder: "content/about"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string"}
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "SEO Title", name: "seotitle", widget: "string"}
      - { label: "SEO Description", name: "seodescription", widget: "string"}
      - { label: "Body", name: "body", widget: "markdown", required: false }
      - label: "About Sections"
        name: "aboutSections"
        widget: 'list'
        types:
          - label: "About Section"
            name: "about-section"
            widget: object
            fields:
              - { label: "Title", name: "title", widget: "string"}
              - { label: "Publish Date", name: "date", widget: "datetime" }
              - { label: "Body", name: "body", widget: "markdown", required: false }
              - { label: "About images", name: "aboutImages", widget: "list", fields: [{label: "Image", name: "image", widget: "image"}], required: false }
      - label: "Studio Sections"
        name: "studioSections"
        widget: 'list'
        types:
          - label: "Studio Section"
            name: "studio-section"
            widget: object
            fields:
              - { label: "Title", name: "title", widget: "string"}
              - { label: "Publish Date", name: "date", widget: "datetime" }
              - { label: "Body", name: "body", widget: "markdown", required: false }
              - { label: "Studio images", name: "studioImages", widget: "list", fields: [{label: "Image", name: "image", widget: "image"}], required: false }
  
  - name: "contact"
    label: "Contact"
    label_singular: "Contact" # Used in the UI, ie: "New Post"
    folder: "content/contact"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string"}
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "SEO Title", name: "seotitle", widget: "string"}
      - { label: "SEO Description", name: "seodescription", widget: "string"}
      - { label: "Body", name: "body", widget: "markdown", required: false }

  - name: "cover"
    label: "Cover"
    label_singular: "Cover" # Used in the UI, ie: "New Post"
    folder: "content/cover"
    media_folder: "{{dirname}}/{{media_folder}}/cover"
    public_folder: "{{public_folder}}/bg"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string"}
      - { label: "Cover", name: "cover", widget: "image"}
  