backend:
  name: git-gateway
  branch: master
media_folder: src/assets
public_folder: assets/images
collections:
  - name: "gallery"
    label: "Gallery"
    label_singular: "Image" # Used in the UI, ie: "New Post"
    folder: "content/gallery"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string"}
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "isDisplay", name: "isDisplay", widget: "boolean", default: false }
      - { label: "Cover", name: "cover", widget: "image"}
      - { label: "Tags", name: "tags", widget: "string" }
  - name: "home"
    label: "Home"
    label_singular: "Home" # Used in the UI, ie: "New Post"
    folder: "content/home"
    media_folder: "{{dirname}}/{{media_folder}}/cover"
    public_folder: "{{public_folder}}/bg"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string"}
      - { label: "Cover", name: "cover", widget: "image"}
      - { label: "Phone Number", name: "phone", widget: "string"}
      - { label: "Headline", name: "headline", widget: "string"}
      - { label: "Body", name: "body", widget: "markdown", required: false }
      - { label: "About Me heading", name: "aboutHeader", widget: "string"}
      - { label: "About Me", name: "about", widget: "markdown", required: false }
      - { label: "About images", name: "aboutImages", widget: "list", fields: [{label: "Image", name: "image", widget: "image"}]}
  - name: "special"
    label: "Special"
    label_singular: "Special" # Used in the UI, ie: "New Post"
    folder: "content/special"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string"}
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Cover", name: "cover", widget: "image", required: false }
      - { label: "Body", name: "body", widget: "markdown", required: false }
  - name: "aboutImages"
    label: "About Images"
    label_singular: "Image" # Used in the UI, ie: "New Post"
    folder: "content/aboutImages"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string"}
      - { label: "Image", name: "image", widget: "image"}
  - name: "about"
    label: "About"
    label_singular: "About" # Used in the UI, ie: "New Post"
    folder: "content/about"
    media_folder: "{{dirname}}/{{media_folder}}/cover"
    public_folder: "{{public_folder}}/bg"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string"}
      - { label: "cover", name: "cover", widget: "image", required: false }
      - { label: "Body", name: "body", widget: "markdown", required: false }
  - name: "studioImages"
    label: "Studio Images"
    label_singular: "Image" # Used in the UI, ie: "New Post"
    folder: "content/studioImages"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string"}
      - { label: "Image", name: "image", widget: "image"}
  - name: "studio"
    label: "Studio"
    label_singular: "Studio" # Used in the UI, ie: "New Post"
    folder: "content/studio"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string"}
      - { label: "Body", name: "body", widget: "markdown", required: false }
  - name: "contact"
    label: "Contact"
    label_singular: "Contact" # Used in the UI, ie: "New Post"
    folder: "content/contact"
    media_folder: "{{dirname}}/{{media_folder}}/cover"
    public_folder: "{{public_folder}}/bg"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string"}
      - { label: "Body", name: "body", widget: "markdown", required: false }
      - { label: "cover", name: "cover", widget: "image", required: false }

